### PR TITLE
[IMP] academic: add regular student certificate

### PR DESCRIPTION
**Pull request by lef-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-academic/pull/113).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-academic#124

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-academic#124

**Pull request closed without merging**
