### PR TITLE
[FIX] odoo-academic: exit_date changed to fields.date

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-academic/pull/77).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#78

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#78

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#78

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#78

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#78

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#78

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#78

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#78

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#78

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#78

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#78

**Pull request closed without merging**
