### PR TITLE
[FW][ADD] academic_sale_subscription: add new module

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-academic#127

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-academic/pull/136).

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jjscarafia cherrypicking of pull request ingadhoc/odoo-academic#127 failed.

* 9e7c686ebf2938c51f103e937aec292637d08921 <- on this commit
* 30dfeb7c2bdd6607f842c2ad04a543ef7d474b18
* a7fc1acc3107fa5f8de278aad491e9be517cebed
* 4e168e60f73a78ca68d41425f53bec5bf93851ed
* 9438947fc2816044c985610e5eba3d789c85641b

stdout:
```
Auto-merging academic/views/res_partner_views.xml
CONFLICT (content): Merge conflict in academic/views/res_partner_views.xml
Auto-merging academic/models/res_partner_link.py

```

stderr:
```
16:18:35.926758 git.c:444               trace: built-in: git cherry-pick 9e7c686ebf2938c51f103e937aec292637d08921
error: could not apply 9e7c686... [ADD] academic_sale_subscription: add new module
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by jjscarafia** [comment]
@roboadhoc r-

**Comment by jjscarafia** [comment]
mezclamos igual porque no está toamndo nueva depenncia que está disponible ya https://github.com/ingadhoc/enterprise-extensions/pull/548 pero no lo toma
total es solo build de smarted, no estamos en producción y vamos a monitorear como queda la main 18 de smarted

**Pull request merged**
