### PR TITLE
[FW][FIX] odoo-academic: exit_date changed to fields.date

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-academic/pull/89).

**Comment by nicomacr** [comment]
@roboadhoc r+ override=ci/runbot-smarted

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr: you are not allowed to override this status.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/runbot-smarted

**Pull request closed without merging**
