### PR TITLE
[IMP] academic: change of dni field type

### PR DESCRIPTION
**Pull request by lef-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-academic/pull/125).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by jjscarafia** [comment]
@roboadhoc r-

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Pull request closed without merging**
