### PR TITLE
[FIX] academic: adapt groups to portal_backend in v16

### PR DESCRIPTION
**Pull request by bruno-zanotti**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-academic/pull/92).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
I'm sorry, @Bruno-Zanotti:
- you can't review+.
- you can't method=rebase-ff.

**Comment by lef-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@Bruno-Zanotti @lef-adhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by lef-adhoc** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by lef-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @lef-adhoc: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
