### PR TITLE
[FW][IMP] academic: multi-company partner category

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-academic#140

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-academic/pull/143).

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jjscarafia cherrypicking of pull request ingadhoc/odoo-academic#140 failed.

stdout:
```
Auto-merging academic/views/res_partner_views.xml
CONFLICT (content): Merge conflict in academic/views/res_partner_views.xml
Auto-merging academic/__manifest__.py
CONFLICT (content): Merge conflict in academic/__manifest__.py

```

stderr:
```
11:51:05.409259 git.c:444               trace: built-in: git cherry-pick 68ef188c1efb17850193293c847128b1fb7b56f9
error: could not apply 68ef188... [IMP] academic: multi-company partner category
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by lef-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by lef-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
