### PR TITLE
[FIX] academic: get_error_messages for more than one partner.

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-academic/pull/74).

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#75
- ingadhoc/odoo-academic#76

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#75
- ingadhoc/odoo-academic#76

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#75
- ingadhoc/odoo-academic#76

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#75
- ingadhoc/odoo-academic#76

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#75
- ingadhoc/odoo-academic#76

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#75
- ingadhoc/odoo-academic#76

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#75
- ingadhoc/odoo-academic#76

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#76

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#76

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#76

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#76

**Pull request closed without merging**
