### PR TITLE
[ADD] academic_sale_subscription: add new module

### PR DESCRIPTION
**Pull request by lef-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-academic/pull/127).

**Comment by jjscarafia** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-academic#136

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-academic#136

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-academic#136

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-academic#136

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-academic#136

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-academic#136

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-academic#136

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-academic#136

**Pull request closed without merging**
