### PR TITLE
[FIX] odoo-academic: remove obsolete method

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-academic/pull/84).

**Comment by JrAdhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#85
- ingadhoc/odoo-academic#86

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#85
- ingadhoc/odoo-academic#86

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#85
- ingadhoc/odoo-academic#86

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#85
- ingadhoc/odoo-academic#86

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#85
- ingadhoc/odoo-academic#86

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#85
- ingadhoc/odoo-academic#86

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#85
- ingadhoc/odoo-academic#86

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#85
- ingadhoc/odoo-academic#86

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#85
- ingadhoc/odoo-academic#86

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#85
- ingadhoc/odoo-academic#86

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#85
- ingadhoc/odoo-academic#86

**Pull request closed without merging**
