### PR TITLE
[FIX] academic: label for student and payment responsible

### PR DESCRIPTION
**Pull request by lef-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-academic/pull/119).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-academic#122

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-academic#122

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-academic#122

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-academic#122

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-academic#122

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-academic#122

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-academic#122

**Pull request closed without merging**
