### PR TITLE
[IMP] academic: usability, companies setup, etc

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-academic/pull/101).

**Comment by lef-adhoc** [comment]
@roboadhoc r+

**Comment by lef-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @lef-adhoc: this PR is already reviewed, reviewing it again is useless.

**Comment by roboadhoc** [comment]
@jjscarafia @lef-adhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by lef-adhoc** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Pull request closed without merging**
