### PR TITLE
[FW][FIX] academic: get_error_messages for more than one partner.

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-academic#74

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-academic/pull/76).

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this PR targets 16.0 and is the last of the forward-port chain containing:
* ingadhoc/odoo-academic#75

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by vib-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by vib-adhoc** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-academic/pull/76).

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc I can only do this on forward-port PRs and this is not one, see roboadhoc.

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr: this PR is already reviewed, reviewing it again is useless.

**Comment by roboadhoc** [comment]
@fw-bot-adhoc @vib-adhoc I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by nicomacr** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@nicomacr I can only do this on forward-port PRs and this is not one, see roboadhoc.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
