### PR TITLE
[FIX] academic: fixes inheritance errors in res_partner view

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-academic/pull/81).

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#82

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#82

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#82

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#82

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#82

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#82

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#82

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#82

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#83

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-academic#83

**Pull request closed without merging**
