### PR TITLE
[FW][FIX] odoo-academic: exit_date changed to fields.date

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-academic#77

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-academic/pull/78).

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr cherrypicking of pull request ingadhoc/odoo-academic#77 failed.

stdout:
```
Auto-merging academic/models/res_partner.py
Auto-merging academic/__manifest__.py
CONFLICT (content): Merge conflict in academic/__manifest__.py

```

stderr:
```
18:49:49.021742 git.c:439               trace: built-in: git cherry-pick 4f223e1f13e6b6314f2a65614c3e40741296b9e8
error: could not apply 4f223e1... [FIX] odoo-academic: exit_date changed to fields.date
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-academic/pull/78).

**Comment by roboadhoc** [comment]
@fw-bot-adhoc I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by nicomacr** [comment]
@fw-bot-adhoc ignore

**Comment by fw-bot-adhoc** [comment]
Forward-port disabled.

**Comment by nicomacr** [comment]
@roboadhoc r+ override=ci/runbot-smarted

**Pull request closed without merging**
